### ISSUE TITLE
Signing and Verifying

### ISSUE THREAD

**Issue by llorllale** [igor-pavlenko/httpsignatures.go#5]
First of all, thank you for this great effort on implementing http signatures!

We're pulling it into a small helper API we're developing over at [TrustBloc](https://github.com/trustbloc/edge-core/pull/107). We noticed the [Sign](https://github.com/igor-pavlenko/httpsignatures-go/blob/0a0c9da171fd4375b804fe6c8b2523483c8109b7/httpsignatures.go#L205-L262) implementation is using the secret key material directly. This blocks its usage in contexts where developers are using KMS APIs that follow current best practice, which include _never_ export your secrets.

Would you guys be open to a PR that changed this such that instead of using a `Secrets` storage it would instead use a supplier of `Signer`s ? The rough outline would be:

1. Fetch the signer using the `keyId`
2. Build the signature string
3. Invoke `s, err := signer.Sign(sigstring)`  

tagging @igor-pavlenko

**Comment by igor-pavlenko** [comment]
Hi George. Thank you for your pull request.

Do you want to store Keys (Public/Private) in secrets storage like Amazon Secrets Manager or Hashicorp Vault instead of storing it directly in the service?

Please, look at:
https://github.com/igor-pavlenko/httpsignatures-go/blob/master/aws/awsSecretsManagerStorage.go

This is like a plugin, it implements an interface to Amazon AWS Secrets Manager (So not private nor public keys stored in service).
You can write your custom Secrets storage, like here: https://github.com/igor-pavlenko/httpsignatures-go#custom-secrets-storage.

If you need help or assistant, please contact me.

**Comment by llorllale** [comment]
Hi @igor-pavlenko 

Yes, we would like to store secrets in external KMS services and HSMs, but we **do not** want to export those secrets outside the KMS service. We want to send the message to be signed over to the remote KMS or HSM. We **do not** want to set [`Secret.PrivateKey`](https://github.com/igor-pavlenko/httpsignatures-go/blob/427f1194d4f0235f1bea788e67733822b8d857ca/secrets.go#L31-L30) because that would expose the secrets from their safe place in the remote KMS/HSM.

**Comment by llorllale** [comment]
This does not mean the existing `Secrets` implementations will not work. It just means the `Sign()` function will not rely on the assumption that it has direct access to the private key.

**Comment by igor-pavlenko** [comment]
Ok, make sense.

What do you think about the following solution:
1) Create custom Secrets Storage (https://github.com/igor-pavlenko/httpsignatures-go#custom-secrets-storage), It will return `Secret` with only KeyID & Algorithm (It's enough for Sign function). But it must return a custom Algorithm, for example: "RSA-SHA512-REMOTE". Full example:
```go
package main

import (
	"github.com/igor-pavlenko/httpsignatures-go"
)

const alg = "RSA-SHA512-REMOTE"

// DummySecretsStorage local files secrets storage
type DummySecretsStorage struct{}

// Get get secret from local files by KeyID
func (s DummySecretsStorage) Get(keyID string) (httpsignatures.Secret, error) {
	return httpsignatures.Secret{
		KeyID:     keyID,
		Algorithm: alg,
	}, nil
}

func main() {
	hs := httpsignatures.NewHTTPSignatures(new(DummySecretsStorage))
}
```

2) Create a custom Signature hash algorithm (https://github.com/igor-pavlenko/httpsignatures-go#custom-signature-hash-algorithm). It will implement
```go
type SignatureHashAlgorithm interface {
	Algorithm() string
	Create(secret Secret, data []byte) ([]byte, error)
	Verify(secret Secret, data []byte, signature []byte) error
}
```
In `Create` you will send `data` (sigstring) to your KMS, get signature and just return it.
Example:
```go
package main

import (
	"bytes"
	"github.com/igor-pavlenko/httpsignatures-go"
)

// Signature Hash algorithm name
const algRsaSha512RemoteName = "RSA-SHA512-REMOTE"

// algRsaSha512Remote RSA-SHA512-REMOTE Algorithm
type algRsaSha512Remote struct{}

// Algorithm Return algorithm name
func (a algRsaSha512Remote) Algorithm() string {
	return algRsaSha512RemoteName
}

// Create Create hash
func (a algRsaSha512Remote) Create(secret httpsignatures.Secret, data []byte) ([]byte, error) {

	signature, err := RemoteKMS.RemoteSign(secret.KeyID, data)
	if err != nil {
		return nil, &httpsignatures.ErrCrypto{Message: "error creating signature", Err: err}
	}

	return signature, nil
}

// Verify Verify hash
func (a algRsaSha512Remote) Verify(secret httpsignatures.Secret, data []byte, signature []byte) error {
	expected, err := a.Create(secret, data)
	if err != nil {
		return err
	}
	res := bytes.Compare(expected, signature)
	if res != 0 {
		return &httpsignatures.ErrCrypto{Message: "wrong signature"}
	}
	
	return nil
}

func main() {
	hs := httpsignatures.NewHTTPSignatures(NewDummySecretsStorage())
	hs.SetSignatureHashAlgorithm(algRsaSha512Remote{})
}
```

**Comment by igor-pavlenko** [comment]
@llorllale But if you can propose a better implementation, please, send me pull request, I will merge it.
Thanks.

**Comment by llorllale** [comment]
@igor-pavlenko thank you for the workaround! Looks like it would work - I will check it out.

I was thinking of a much bigger change to the interfaces but your suggestion will certainly unblock us.
